# ShorelineMonitor: Satellite-Derived Shoreline-Series

The
[ShorelineMonitor-Shorelines](https://radiantearth.github.io/stac-browser/#/external/coclico.blob.core.windows.net/stac/v1/shorelinemonitor-shorelines/collection.json)
dataset provides Satellite-Derived Shorelines (SDS) extracted from annually composited
Landsat satellite imagery spanning the years 1984-2024. These shorelines are mapped onto
the [Global Coastal Transect System
(GCTS)](https://github.com/TUDelft-CITG/coastpy/blob/main/tutorials/global_coastal_transect_system.ipynb).
Together they compose a new dataset that consists of time series per transect.
The ShorelineMonitor-Series consists of more than 350 million observations, each with 54
attributes, accross almost 7.5 million transects. The dataset and attributes are described in this [STAC
collection](https://radiantearth.github.io/stac-browser/#/external/coclico.blob.core.windows.net/stac/v1/shorelinemonitor-series/collection.json).
Please have a look at the metadata in one of the items. The dataset is available upon reasonable request. Please contact the data provider for more information or collaboration opportunities.

In [1]:
import os

import dotenv
import fsspec
import geopandas as gpd
import hvplot.pandas
import pandas as pd
import pystac
import shapely
from dotenv import load_dotenv
from ipyleaflet import Map, basemaps

from coastpy.stac.utils import read_snapshot

load_dotenv()

# Configure cloud and Dask settings
sas_token = os.getenv("AZURE_STORAGE_SAS_TOKEN")
storage_options = {"account_name": "coclico", "sas_token": sas_token}

coclico_catalog = pystac.Catalog.from_file(
    "https://coclico.blob.core.windows.net/stac/v1/catalog.json"
)
collection = coclico_catalog.get_child("shorelinemonitor-series")

In [2]:
snapshot = read_snapshot(collection, storage_options=storage_options)
snapshot.head()

,type,stac_version,stac_extensions,id,geometry,bbox,links,assets,collection,created,table:columns,proj:bbox,proj:epsg,start_datetime,end_datetime,table:row_count,datetime,href,alternate_href
0,Feature,1.0.0,[https://stac-extensions.github.io/table/v1.2....,box_028_s54w75-66fa8f,"POLYGON ((-72.44845 -53.92088, -72.44845 -47.3...","[-75.3026602111646, -53.92087793434633, -72.44...",[{'href': 'https://coclico.blob.core.windows.n...,{'data': {'description': 'Parquet dataset cont...,shorelinemonitor-series,2025-01-20 20:18:09.036992+00:00,[{'description': 'Unique identifier for the tr...,"[-75.3026602111646, -53.92087793434633, -72.44...",4326,1984-01-01 00:00:00+00:00,2023-01-01 00:00:00+00:00,991008,2003-07-02 12:00:00+00:00,az://shorelinemonitor-series/release/2025-01-0...,https://coclico.blob.core.windows.net/shorelin...
1,Feature,1.0.0,[https://stac-extensions.github.io/table/v1.2....,box_028_s54w75-917447,"POLYGON ((-72.00235 -53.73197, -72.00235 -47.3...","[-75.00581816899678, -53.73196646975179, -72.0...",[{'href': 'https://coclico.blob.core.windows.n...,{'data': {'description': 'Parquet dataset cont...,shorelinemonitor-series,2025-01-20 20:18:27.328573+00:00,[{'description': 'Unique identifier for the tr...,"[-75.00581816899678, -53.73196646975179, -72.0...",4326,1984-01-01 00:00:00+00:00,2023-01-01 00:00:00+00:00,991035,2003-07-02 12:00:00+00:00,az://shorelinemonitor-series/release/2025-01-0...,https://coclico.blob.core.windows.net/shorelin...
2,Feature,1.0.0,[https://stac-extensions.github.io/table/v1.2....,box_028_s54w75-d7a28b,"POLYGON ((-71.86633 -54.44184, -71.86633 -47.9...","[-75.46160418213485, -54.44183652936649, -71.8...",[{'href': 'https://coclico.blob.core.windows.n...,{'data': {'description': 'Parquet dataset cont...,shorelinemonitor-series,2025-01-20 20:18:44.925111+00:00,[{'description': 'Unique identifier for the tr...,"[-75.46160418213485, -54.44183652936649, -71.8...",4326,1984-01-01 00:00:00+00:00,2023-01-01 00:00:00+00:00,990994,2003-07-02 12:00:00+00:00,az://shorelinemonitor-series/release/2025-01-0...,https://coclico.blob.core.windows.net/shorelin...
3,Feature,1.0.0,[https://stac-extensions.github.io/table/v1.2....,box_028_s54w76-051a7a,"POLYGON ((-71.86565 -54.39095, -71.86565 -47.6...","[-75.63563555396445, -54.39095345035114, -71.8...",[{'href': 'https://coclico.blob.core.windows.n...,{'data': {'description': 'Parquet dataset cont...,shorelinemonitor-series,2025-01-20 20:19:05.157030+00:00,[{'description': 'Unique identifier for the tr...,"[-75.63563555396445, -54.39095345035114, -71.8...",4326,1984-01-01 00:00:00+00:00,2023-01-01 00:00:00+00:00,991037,2003-07-02 12:00:00+00:00,az://shorelinemonitor-series/release/2025-01-0...,https://coclico.blob.core.windows.net/shorelin...
4,Feature,1.0.0,[https://stac-extensions.github.io/table/v1.2....,box_028_s54w76-936812,"POLYGON ((-71.98706 -54.21485, -71.98706 -47.8...","[-75.59448237358822, -54.21485456999666, -71.9...",[{'href': 'https://coclico.blob.core.windows.n...,{'data': {'description': 'Parquet dataset cont...,shorelinemonitor-series,2025-01-20 20:19:24.514354+00:00,[{'description': 'Unique identifier for the tr...,"[-75.59448237358822, -54.21485456999666, -71.9...",4326,1984-01-01 00:00:00+00:00,2023-01-01 00:00:00+00:00,991030,2003-07-02 12:00:00+00:00,az://shorelinemonitor-series/release/2025-01-0...,https://coclico.blob.core.windows.net/shorelin...

## Spatial partitions

This map shows the spatial partitions. In this release we have prioritized having unique transect_ids per partition over geospatial sorting. As a result there are overlapping partitions. This can be improved in the future.

In [3]:
snapshot.hvplot(geo=True, tiles="OSM", line_color="black", fill_alpha=0.2)

:Overlay
   .WMTS.I     :WMTS   [Longitude,Latitude]
   .Polygons.I :Polygons   [Longitude,Latitude]

## Select a region of interest

Wait for the map to render and zoom to area of interest.

In [4]:
from ipyleaflet import Map, basemaps

m = Map(basemap=basemaps.Esri.WorldImagery, scroll_wheel_zoom=True)
m.center = (43.32, -1.97)
m.zoom = 14
m.layout.height = "800px"
m

Map(center=[43.32, -1.97], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_o…

In [5]:
from coastpy.geo.utils import get_region_of_interest_from_map

roi = get_region_of_interest_from_map(m, default_extent=(4.796, 53.108, 5.229, 53.272))
west, south, east, north = list(roi.total_bounds)

m.center = (43.32, -1.97)
m.zoom = 14.0
west, south, east, north = (-2.018, 43.295, -1.922, 43.345)

## Fetch data

In [23]:
import coastpy

db = coastpy.io.STACQueryEngine(
    stac_collection=collection,
    storage_backend="azure",
    # columns = ["geometry", "transect_id", "sds:change_rate"]  # ... # when you don't need all data
)

In [24]:
from coastpy.utils.config import fetch_sas_token

sas_token = fetch_sas_token(sas_token)
df = db.get_data_within_bbox(west, south, east, north, sas_token=sas_token)
print(f"Shape: {df.shape}")
df.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Shape: (7618, 54)

,transect_id,shoreline_id,obs_id,datetime,geometry,lon,lat,shoreline_position,chainage,utm_epsg,...,offshore_domain,otsu_threshold,otsu_separability,composite:start_datetime,composite:end_datetime,composite:determination_datetimes,composite:image_id,composite:cloud_cover,country,common_country_name
0,cl30793s01tr02926965,box_164_212-08761-35248,cl30793s01tr02926965_00050,2014-01-01,POINT (-1.92221 43.33598),-1.922210,43.335979,102.768555,1010.803467,32630,...,NaN,0.000000,1.615540,2014-01-10 11:45:03+01:00,2014-12-28 11:47:06+01:00,"[2014-01-10T10:45:03.000000, 2014-01-17T10:51:...",2014-01-01-2015-01-01_IM_L5,"[36, 58, 70.62000274658203, 57, 35, 74.0199966...",ES,Spain
1,cl30793s01tr02927065,box_164_212-08731-35473,cl30793s01tr02927065_00000,1984-01-01,POINT (-1.92242 43.33497),-1.922424,43.334969,-28.933899,929.658020,32630,...,NaN,0.031250,1.622497,1984-04-12 12:21:57+02:00,1984-12-17 11:18:43+01:00,"[1984-04-12T10:21:57.000000, 1984-04-21T10:15:...",1984-01-01-1984-12-31_IM_L5,"[49, 1, 21, 24, 0, 49, 17, 8, 9, 0, 60, 56, 0,...",ES,Spain
2,cl30793s01tr02927065,box_164_212-08732-35466,cl30793s01tr02927065_00001,1985-01-01,POINT (-1.92232 43.33491),-1.922321,43.334911,-39.317383,919.274536,32630,...,NaN,0.019531,1.614311,1985-01-02 11:18:51+01:00,1985-12-04 11:16:46+01:00,"[1985-01-02T10:18:51.000000, 1985-01-09T10:25:...",1985-01-01-1986-01-01_IM_L5,"[60, 38, 56, 49, 25, 53, 67, 12, 70, 48, 60, 0...",ES,Spain
3,cl30793s01tr02927065,box_164_212-08733-35457,cl30793s01tr02927065_00002,1986-01-01,POINT (-1.92253 43.33502),-1.922528,43.335022,-18.553162,940.038757,32630,...,NaN,-0.023438,1.643283,1986-02-22 11:15:07+01:00,1986-12-30 11:14:02+01:00,"[1986-02-22T10:15:07.000000, 1986-03-26T10:14:...",1986-01-01-1987-01-01_IM_L5,"[34, 46, 34, 59, 45, 43, 60, 60, 22, 57, 12, 2...",ES,Spain
4,cl30793s01tr02927065,box_164_212-08734-35481,cl30793s01tr02927065_00005,1987-01-01,POINT (-1.92243 43.33497),-1.922427,43.334969,-28.672729,929.919189,32630,...,NaN,0.007812,1.618580,1987-01-31 11:14:56+01:00,1987-12-01 11:23:07+01:00,"[1987-01-31T10:14:56.000000, 1987-02-09T10:09:...",1987-01-01-1988-01-01_IM_L5,"[61, 10, 33, 33, 50, 22, 12, 37, 31, 53, 60, 0...",ES,Spain

## Explore data in a dashboard

In [25]:
from coastpy.viz.dashboard import ShorelineSeriesApp

ShorelineSeriesApp(df).show()

C:\Users\kras\AppData\Local\mambaforge\envs\coastal\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\kras\AppData\Local\mambaforge\envs\coastal\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\kras\AppData\Local\mambaforge\envs\coastal\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

Launching server at http://localhost:62724

In [11]:
select = df[df.transect_id == "cl30793s01tr02935165"]

In [17]:
select.iloc[0].keys()

Index(['transect_id', 'shoreline_id', 'obs_id', 'datetime', 'geometry', 'lon',
       'lat', 'shoreline_position', 'chainage', 'utm_epsg', 'transect_lon',
       'transect_lat', 'transect_quadkey', 'quadkey', 'bbox', 'sinuosity',
       'self_intersection_density', 'fractal_dimension', 'is_shoal',
       'obs_group', 'obs_group_stdev', 'obs_group_range', 'obs_group_count',
       'obs_is_qa', 'obs_is_primary', 'obs_is_step_change', 'obs_is_outlier',
       'obs_count', 'obs_mdn_offset', 'subseries_id', 'reference_datetime',
       'reference_chainage', 'reference_lon', 'reference_lat',
       'obs_primary_count', 'obs_primary_mdn', 'tr_stdev', 'tr_range',
       'tr_qa_pct', 'tr_is_qa', 'dist_b330', 'dist_b0', 'dist_b30', 'min_dist',
       'offshore_domain', 'otsu_threshold', 'otsu_separability',
       'composite:start_datetime', 'composite:end_datetime',
       'composite:determination_datetimes', 'composite:image_id',
       'composite:cloud_cover', 'country', 'common_country_name'],
      dtype='object')

## Process the dataset in bulk

In [ ]:
import dask_geopandas

fs = fsspec.filesystem("az", **storage_options)

urlpaths = snapshot.href.to_list()

ddf = dask_geopandas.read_parquet(urlpaths, filesystem=fs)
ddf

In [ ]:
def process(df):
    # your code comes here
    ...
    return df


result = ddf.map_partitions(process)